Traceback (most recent call last):
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 194, in <module>
    main(sys.argv)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 89, in main
    pass_num, total = run(DIRECTORY, PROJECT, IDX)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 101, in run
    if project in skip_list :
NameError: name 'skip_list' is not defined
[36m[[[tornado-1689]]][0m
Time :  7.23 seconds
Traceback (most recent call last):
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1977, in _communicate
    ready = selector.select(timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 195, in <module>
    main(sys.argv)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 88, in main
    pass_num, total = run(DIRECTORY, PROJECT, IDX)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 174, in run
    works.work()
  File "/home/wonseok/pyfix/my_tool/work.py", line 305, in work
    synthe.synthesize(node, neg_filename, neg_funcname, neg_classname, neg_args, self.pos_func_infos, None, None)
  File "/home/wonseok/pyfix/my_tool/synthesizer/synthesize.py", line 96, in synthesize
    temp_synthesize.template_synthesize(node)
  File "/home/wonseok/pyfix/my_tool/synthesizer/template_synthesizer.py", line 261, in template_synthesize
    self.validation(node, target)
  File "/home/wonseok/pyfix/my_tool/synthesizer/template_synthesizer.py", line 230, in validation
    self.validator.validate(node, self.filename, target)
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 78, in validate
    if self.validate_neg() and self.validate_pos() :
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 41, in validate_neg
    out, err = self.exec_prog.execute_neg()
  File "/home/wonseok/pyfix/my_tool/execute.py", line 27, in execute_neg
    out, err = result.communicate()
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1141, in communicate
    self._wait(timeout=sigint_timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1909, in _wait
    time.sleep(delay)
KeyboardInterrupt
[36m[[[airflow-3831]]][0m
Time :  2.48 seconds
Traceback (most recent call last):
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 209, in <module>
    main(sys.argv)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 80, in main
    pass_num, total = run(DIRECTORY, PROJECT, IDX)
  File "/home/wonseok/pyfix/my_tool/./test_main.py", line 188, in run
    works.work()
  File "/home/wonseok/pyfix/my_tool/work.py", line 347, in work
    synthe.synthesize(node, neg_filename, neg_funcname, neg_classname, neg_args, self.pos_func_infos, None, context_aware, None, self.neg_additional)
  File "/home/wonseok/pyfix/my_tool/synthesizer/synthesize.py", line 96, in synthesize
    temp_synthesize.template_synthesize(node)
  File "/home/wonseok/pyfix/my_tool/synthesizer/template_synthesizer.py", line 379, in template_synthesize
    self.validation(node, targets)
  File "/home/wonseok/pyfix/my_tool/synthesizer/template_synthesizer.py", line 320, in validation
    self.validator.validate(node, self.filename, target)
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 79, in validate
    if self.validate_neg() and self.validate_pos() :
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 41, in validate_neg
    out, err = self.exec_prog.execute_neg()
  File "/home/wonseok/pyfix/my_tool/execute.py", line 35, in execute_neg
    out, err = result.communicate()
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1977, in _communicate
    ready = selector.select(timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
[36m[[[pandas-19276]]][0m
Time :  1.21 seconds
Traceback (most recent call last):
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 340, in <module>
    main(sys.argv)
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 182, in main
    pass_num, total = run(DIRECTORY, BENCHMARK, PROJECT, IDX, [], ASSERT)
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 315, in run
    works.work()
  File "/home/wonseok/pyfix/my_tool/work.py", line 892, in work
    self.msg_patch(synthe)
  File "/home/wonseok/pyfix/my_tool/work.py", line 267, in msg_patch
    self.validate.multiple_file_validate(node, all_targets, test, self.total_test_num)
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 142, in multiple_file_validate
    if self.validate_neg(test, total_test_num) and self.validate_pos() :
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 52, in validate_neg
    out, err = self.exec_prog.execute_neg()
  File "/home/wonseok/pyfix/my_tool/execute.py", line 44, in execute_neg
    out, err = result.communicate()
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1977, in _communicate
    ready = selector.select(timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
[36m[[[pandas-25759]]][0m
Time :  7.77 seconds
Traceback (most recent call last):
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 340, in <module>
    main(sys.argv)
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 182, in main
    pass_num, total = run(DIRECTORY, BENCHMARK, PROJECT, IDX, [], ASSERT)
  File "/home/wonseok/pyfix/my_tool/test_main.py", line 315, in run
    works.work()
  File "/home/wonseok/pyfix/my_tool/work.py", line 1560, in work
    pos_guard()
  File "/home/wonseok/pyfix/my_tool/work.py", line 1519, in pos_guard
    pos_onlyguard()
  File "/home/wonseok/pyfix/my_tool/work.py", line 1509, in pos_onlyguard
    self.validate.validate(node, neg_filename, targets, test, self.total_test_num)
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 178, in validate
    if self.validate_neg(test, total_test_num) and self.validate_pos() :
  File "/home/wonseok/pyfix/my_tool/synthesizer/validator.py", line 115, in validate_neg
    out, err = self.exec_prog.execute_neg()
  File "/home/wonseok/pyfix/my_tool/execute.py", line 44, in execute_neg
    out, err = result.communicate()
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1130, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 1977, in _communicate
    ready = selector.select(timeout)
  File "/home/wonseok/.pyenv/versions/3.9.1/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
